### ISSUE TITLE
Trailing slashes in context URLs

### ISSUE THREAD

**Issue by bronger** [TheELNConsortium/TheELNFileFormat#21]
After having serious trouble exporting correct JSON-LD, I think the RO-Crate spec has an error: The `@context` URIs should end in a “/”, shouldn’t they? For instance:

```json
{                                                                                                                                             
  "@context": {                                                                                                                               
    "@vocab": "https://w3id.org/ro/crate/1.1/context/",                                                                                       
    "sm": "http://scimesh.org/SciMesh/"                                                                                                       
  },                                                                                                                                          
  "@graph": [                                                                                                                                 
    {
```

**Comment by NicolasCARPi** [comment]
No I don't think context URIs should end with a `/`, but that's my 2 cents.

For data entities, it's a SHOULD, see https://github.com/ResearchObject/ro-crate/issues/59.

What kind of troubles did you encounter and wouldn't the use of a function like `joinPath` remove the importance of having a trailing slash or not?

Looking around, it doesn't seem that there is a consensus on trailing vs not trailing slash for URI.

**Comment by bronger** [comment]
I did some research and the problem is that the `@context` entry is rather overloaded. If it is a mere string, it is treated as a URL from which the names are downloaded. However, if it is a map, any map entry that is used as a namespace prefix or the key of which is `@vocab` is treated as an IRI fragment that needs to end in a `#` or `/` in oder to work as an abbreviation.
