### ISSUE TITLE
List ELN implementations

### ISSUE THREAD

**Issue by stain** [TheELNConsortium/TheELNFileFormat#61]
Hi, would you be able to list/link implementations of TheELNFileFormat on the README? 

The challenge is that "ELN" is an overloaded terms so it's a bit tricky to check in docs or google..

So far I think the implementations are:  [eLabFTW](https://doc.elabftw.net/user-guide.html#export-button), [RSpace](https://documentation.researchspace.com/article/s3j29if453-export-formats), PASTA-ELN (documentation link?)

https://github.com/TheELNConsortium/#participating-eln-projects has a bit more but I guess not all have implemented ELN format yet.

Then I can update https://github.com/ResearchObject/ro-crate/blob/master/docs/profiles.md#electronic-lab-notebook-eln or make a separate "in-use" page from the RO-Crate web site to help promote further.

Citations like https://doi.org/10.1186/s13326-021-00257-x would also be useful to capture!

**Comment by FlorianRhiem** [comment]
In addition to the ones you've listed, [SampleDB](https://go.fzj.de/sampledb) and [Kadi4Mat](https://kadi.iam.kit.edu/) both implement the format and have example files in the [examples](https://github.com/TheELNConsortium/TheELNFileFormat/tree/master/examples) folder.

**Comment by NicolasCARPi** [comment]
Maybe changing the README to have a table with checkmarks for support would be good. IIRC we discussed that at our previous meeting. Columns could be: Vendor, URL, .eln import, .eln export

And row values could be a green checkmark or red cross or something in-between, to reflect the state of the current implémentation.

**Comment by SteffenBrinckmann** [comment]
Hey, 
automatic reporting: there is a github action that lists all solutions that started working on the .eln implementation 
-> https://github.com/TheELNConsortium/TheELNFileFormat/actions/runs/7568702576
But linking to the latest github action solution is not trivial and linking to a dynamically generated table is error-prone.

Self-reporting has its advantages and disadvantages, but can capture export and import functionality.

I would suggest @stain to make a suggestion of would style of table you would prefer  and then we can adopt it.

**Comment by NicolasCARPi** [comment]
Would something like this be a good start?

|          | Website                                | .eln export | .eln import |
|:--------:|----------------------------------------|:-----------:|:-----------:|
|  eLabFTW | https://www.elabftw.net                |      ✅      |      ✅      |
| Kadi4Mat | https://kadi.iam.kit.edu/              |      ✅      |      ✅      |
| Pasta    | https://github.com/PASTA-ELN/pasta-eln |      ✅      |      ✅      |
| SampleDB | https://github.com/sciapp/sampledb     |      ✅      |      ✅      |
| Rspace   | https://www.researchspace.com/         |      ✅      |      ✅      |
